### ISSUE TITLE
Example 10->file_path and folder ../data/general not included

### ISSUE THREAD

**Issue by AlexTsev688** [tyiannak/multimodalAnalysis#14]
Hello, I am from the MsC !

**Example 10->male and female sound files don't exist in the path given and folder ../data/general not included**
The dir "../data/general" doesn't exist. Also when I tried to check in the dir "../data/gender/..", only this file exists m1_neu-m1-l1.wav.wav. I can't find f1_neu-f1-l2.wav.wav, it seems that there are similar female sound wav files but they are not the same.

```
fp1 = "../data/general/speech/m1_neu-m1-l1.wav.wav" # male
fp2 = "../data/general/speech/f1_neu-f1-l2.wav.wav" # female
```

**Comment by tyiannak** [comment]
Hi thanx for the question.
Unfortunately, I am not quite sure I have the right to just add the samples I've used for these examples, but you can get them from here http://emodb.bilderbar.info/index-1024.html
